### ISSUE TITLE
Transfer the repository to @sass organization?

### ISSUE THREAD

**Issue by dahlia** [sass/libsass-python#108]
We have now more than one maintainers, so I’m not sure whether this repository still should belong to @dahlia.  There's the official organization named @sass, which consists of libsass upstream itself, and several bindings of it e.g. node-sass, perl-libsass, ruby-libsass.  I think @sass would be the best place to transfer this repository to, but wonder others' opinions about the idea.  Also, I have currently no idea how we can even if we want to do it.

**Comment by dahlia** [comment]
Plus: although it might be somewhat off-topic, `maintainer` of the package metadata (described in setup.py) should contain @asottile.

**Comment by mgreter** [comment]
AFAIK @hcatlin would be the right contact. Easiest probably by our [slack channel] [1].

[1]: https://libsass.slack.com

**Comment by jleclanche** [comment]
Any update on this?

**Comment by asottile** [comment]
I'm not entirely convinced.  The current repositories contain bindings maintained by the core libsass maintainers.  This repository doesn't quite fit that as well

**Comment by dahlia** [comment]
Wonder if the binding maintainers became core libsass maintainers, or core libsass maintainers also made bindings as well.

**Comment by mgreter** [comment]
@asottile would you like to give this another shot. You definitively would have my support. Unfortunately the perl bindings (which I maintain) are not as popular as your python binding (due to obvious reasons, perl5 just isn't the cool kid on the block anymore 😉). BTW. would really love to ask if you'd be willing to try to integrate native libsass plugins as I did with perl-libsass!? If you're willing to give it a shot either way, count on my support. I really admire what you achieved with the LibSass API so far. Well Done 👍 :clap:

**Comment by asottile** [comment]
I'd be happy to join the org, I'm not sure why I had concerns before but I don't have any now :)

@dahlia owns the repository and would be the contact for transferring it.

Looking forward to the org 🎉 

As for native extensions, I'll check out how the perl bindings does them and see if we can fit them in here too!

**Comment by mgreter** [comment]
Cool. For the native extensions: They basically just need to be compiled with the same toolchain and the same main libsass dependency into dynamic objects to be loaded via plugin paths. But to conserve disk space it makes sense to have all parts link to the same shared libsass library (was the hardest part in perl-libsass build, but static linking also works).

**Comment by mgreter** [comment]
//CC @nex3 @chriseppstein @xzyfer for transfer to the sass org!

**Comment by xzyfer** [comment]
I can take care of this tonight.

**Comment by xzyfer** [comment]
Had a look. I think the owner/admin of this repo needs to request the transfer, then I can accept it.

**Comment by dahlia** [comment]
Sorry for late response.  I've just tried to transfer ownership to @sass, but it failed with an error message:

![“You don’t have the permission to create repositories on sass”](https://user-images.githubusercontent.com/12431/34886760-71b9c990-f807-11e7-922b-24b847dd93c1.png)

Is there an other way to “request” the transfer?

**Comment by asottile** [comment]
Ah yes, @dahlia needs to be a member of @sass to be able to transfer to it -- I recall this from moving repositories in/out of orgs before.

**Comment by xzyfer** [comment]
Ok cool. I'll add you to the sass org in my morning.

On 13 Jan. 2018 4:41 am, "Anthony Sottile" <notifications@github.com> wrote:

Ah yes, @dahlia <https://github.com/dahlia> needs to be a member of @sass
<https://github.com/sass> to be able to transfer to it -- I recall this
from moving repositories in/out of orgs before.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dahlia/libsass-python/issues/108#issuecomment-357302318>,
or mute the thread

**Comment by xzyfer** [comment]
Still working on this. I haven't forgotten.

**Comment by xzyfer** [comment]
Looks like the easiest way to do this may be to add me as a collaborator and I should be able to do a transfer requests.

**Comment by asottile** [comment]
Collaborator won't have access to that setting -- would need to be added as an _owner_

**Comment by xzyfer** [comment]
Aha ok I managed to the Sass org permissions sorted out. @dahlia you should have an invite to join the Sass org.

**Comment by dahlia** [comment]
I've just received the invitation and joined the org now. I'll transfer the repo right now.

**Comment by dahlia** [comment]
Hmm… it still says:

> You don’t have the permission to create repositories on sass

even though I now belong to the @sass org.

**Comment by xzyfer** [comment]
Ok try now.

**Comment by dahlia** [comment]
Weird. Still the same error occurs:

> You don’t have the permission to create repositories on sass

**Comment by xzyfer** [comment]
There isn't anything else I can seemingly do in the Sass org. Maybe try
logging out of GitHub?

Otherwise all I can think of is making me an owner of this repo so tasty I
can the transfer.

**Comment by chriseppstein** [comment]
> Users must have repository creation permissions within the receiving organization before they can transfer a repository that they individually own. If Allow members to create repositories for this organization has been disabled in the receiving organization, only organization owners can transfer repositories into the organization.

We have this setting off. I will enable it for this transfer and then disable it after it's complete.

**Comment by xzyfer** [comment]
Aha. Thanks @chriseppstein. I've been fumbling around the GH UI for a while now :/

**Comment by dahlia** [comment]
Thanks for you all! We've just transferred the repository to @sass org finally!

As we changed the url, there could be several things to do. I'll list them in #229.

**Comment by chriseppstein** [comment]
🎉

**Comment by xzyfer** [comment]
Thanks everyone! Welcome to the team @dahlia

**Comment by asottile** [comment]
🎉 (do I get an invite too? 😆)

**Comment by xzyfer** [comment]
@asottile aha I thought you were already in the org because of your work LibSass. I've added you to the sass/libsass-python team. Check your inbox :)
