### ISSUE TITLE
Python script sassc renaming ?

### ISSUE THREAD

**Issue by frediz** [sass/libsass-python#134]
Hi,
libsass-python provides a sassc utility in python.
The name "sassc" means "Sass implemented in C", and it can collide with the binary sassc from the original project in C, when installing.
Would it make sense to rename the python utility from sassc to pysassc ?

Fred

**Comment by dahlia** [comment]
> The name "sassc" means "Sass implemented in C"

I’ve though `sassc` means “SASS Compiler,” although, yes, it can collide with `sassc` provided by [SassC][].  Its main purpose is to provide a drop-in-replacement of that.

[SassC]: https://github.com/sass/sassc

**Comment by frediz** [comment]
I see.
So is there some plan to make the command line utilities converge ?
Because at the moment, python sassc is not totally a replacement to sassc.
In the versions below, the usage are a bit different : 

sassc 3.3.2 : 
---
Usage: sassc [options] [INPUT] [OUTPUT]

Options:
   -s, --stdin             Read input from standard input instead of an input file.
   -t, --style NAME        Output style. Can be: nested, expanded, compact, compressed.
   -l, --line-numbers      Emit comments showing original line numbers.
       --line-comments
   -I, --load-path PATH    Set Sass import path.
   -P, --plugin-path PATH  Set path to autoload plugins.
   -m, --sourcemap         Emit source map.
   -M, --omit-map-comment  Omits the source map url comment.
   -p, --precision         Set the precision for numbers.
   -v, --version           Display compiled versions.
   -h, --help              Display this help message.
---

sassc 0.9.3 from libsass-python : 
---
Usage: sassc [options] SCSS_FILE [OUT_CSS_FILE]

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -s STYLE, --output-style=STYLE
                        Coding style of the compiled result.  Choose one of
                        nested, expanded, compact, or compressed. [default:
                        nested]
  -m, -g, --sourcemap   Emit source map.  Requires the second argument (output
                        css filename).
  -I DIR, --include-path=DIR
                        Path to find "@import"ed (S)CSS source files.  Can be
                        multiply used.
  -w, --watch           Watch file for changes.  Requires the second argument
                        (output css filename).
  -p PRECISION, --precision=PRECISION
                        Set the precision for numbers. [default: 5]
---

**Comment by dahlia** [comment]
I believe all options provided by SassC except `-P`/`--plugin-path` can be covered.

**Comment by asottile** [comment]
fwiw I kind of agree with @frediz -- perhaps we can have a migration period where we provide `pysassc` and `sassc` (the debian packaging can choose to delete `sassc` so we don't conflict with https://github.com/sass/sassc) and we can phase out `sassc` over a few releases

**Comment by dahlia** [comment]
If we had some statistics about its usage the decision could be way
easier.  Although it’s just an anecdote of mine, some private projects of
my work actually use libsass-python’s sassc command.  Thanks to its
compatible interface to the original sassc command, I don’t have to install
the original one, but libsass-python is enough to run these programs (which
internally popens sassc command).  I am not sure whether it’s just me or
typical usage, but if it’s not that unusual way to use it I also agree to
rename the command to pysassc.  😉

**Comment by asottile** [comment]
Here's the release plan for this [from here](https://github.com/dahlia/libsass-python/pull/218#issuecomment-330957597):

> - next release: add `pysassc`
> - next next release: issue deprecation warning in `sassc`
> - (some time after): change warning to error
> - (some time after): remove `sassc`

**Comment by mgreter** [comment]
FWIW. I named the cli tool in perl-libsass "psass". I would probably have named the python cli the same, but maybe `pysass` would also be an option (not sure why you want to keep the "c" in there)? Since perl-libsass includes the complete libsass dependency, it optionally also can compile/install the official sassc binary (which links to the same libsass library as perl consumes). This is especially useful to share the same plugins (also in the same .so/.dll/.dynlib format, linking to the one shared LibSass lib). This way one can install the complete LibSass ecosystem by installing the perl bindings via cpan. I believe a similar approach might be possible for python-libsass, although I have to say it required quite some tinkering with the build system for the [perl bindings][1]. But after some try and error it works now on all major systems (linux/windows/osx).

[1]: https://github.com/sass/perl-libsass/blob/develop/Makefile.PL#L577-L736

**Comment by asottile** [comment]
Sounds good -- we're in the migration process to an executable named `pysassc` (python sass compiler) and will be slowly deprecating and phasing out the old name.  🔜 ™️
