### ISSUE TITLE
The repository url was moved to github.com/sass/libsass-python; Things to do

### ISSUE THREAD

**Issue by dahlia** [sass/libsass-python#229]
Change the following links:

- [x] The website url from PyPI package page
- [x] The docs url from README.rst and PyPI package page (or is it chance to resolve #91?)
- [x] Make redirection from <https://hongminhee.org/libsass-python/> (it's now 404!)
- [x] Figure out if appveyor is actually working
- [x] URL in repository description

Any others?

**Comment by asottile** [comment]
Added an action item: I'm not convinced appveyor is working... There are builds [here](https://ci.appveyor.com/project/asottile/libsass-python) but they are all manually triggered by me.

I wonder if there's something that needs to happen from the repository side.  It might also be something got stuck on the appveyor side as I had to link / unlink several times for the url to not have five random characters at the end.

**Comment by asottile** [comment]
ah yes probably, I'll ping @xzyfer on twitter with the url (I think it's secret? not entirely sure)

**Comment by asottile** [comment]
until then, I can just push the buttons so we can run a ~noop release to change all the urls

**Comment by asottile** [comment]
@xzyfer temporarily granted me privileges and I updated the url.  seems to be working! https://ci.appveyor.com/project/asottile/libsass-python/build/1.0.3

**Comment by dahlia** [comment]
Would GitHub Pages work if I create a directory named `libsass-python` into dahlia/dahlia.github.io repository (which is associated to hongminhee.org domain)?  I will experiment with this tonight (I'm at KST +09:00).

**Comment by asottile** [comment]
seems the new gh-pages is functional at https://sass.github.io/libsass-python

perhaps it is time to switch to rtd?  I started setting it up again but it requires admin for webhooks again (lol).

I'm going to cut a trivial release so we can at least get the urls updated

**Comment by dahlia** [comment]
Okay, I've just made redirections from old urls to new urls, e.g.:

- <https://hongminhee.org/libsass-python/> → <https://sass.github.io/libsass-python/>
- <https://hongminhee.org/libsass-python/sass.html#sass.compile> → <https://sass.github.io/libsass-python/sass.html#sass.compile>
- <https://hongminhee.org/libsass-python/search.html?q=compile> → <https://sass.github.io/libsass-python/search.html?q=compile>

**Comment by asottile** [comment]
I made a release so the pypi links and doc links are updated.  I think (?) all that's left is to change the url in the repository description and probably update https://github.com/sass/sass-site

**Comment by asottile** [comment]
@dahlia do you have permission to edit the repo description or do we need to escalate to do that (that's the last action item afaik!)

**Comment by dahlia** [comment]
I have no permission.  Could @xzyfer change the url in the repo description to <https://sass.github.io/libsass-python/>?

**Comment by xzyfer** [comment]
Try now @dahlia

**Comment by dahlia** [comment]
Now I have permission. Thanks @xzyfer!

Changed the url as well.
