### ISSUE TITLE
Broken url in docs

### ISSUE THREAD

**Issue by garyvdm** [sass/libsass-python#231]
In this section of the docs: https://sass.github.io/libsass-python/sass.html#sass.compile

There is a link to "importer callbacks" which goes to https://sass.github.io/libsass-python/importer-callbacks which returns 404.

**Comment by asottile** [comment]
Strange, all the internal links on that page are broken. I wonder if I generated it with an old version of sphinx. I'll check this when I'm at a computer, thanks for the issue!

**Comment by asottile** [comment]
Fixed it using [this trick](https://stackoverflow.com/questions/36539740/internal-hyperlink-in-restructuredtext-with-customized-text).

rst+-
