### ISSUE TITLE
How to use normal sass rather than scss?

### ISSUE THREAD

**Issue by NoorMkdad** [sass/libsass-python#238]
How do I use normal SASS syntax rather than SCSS?

**Comment by asottile** [comment]
For use with [`sass.compile`](https://sass.github.io/libsass-python/sass.html#sass.compile) you want the `indented=True` kwarg.

I think for `compile(filename=...)` it might have some auto-detection if the filename ends with`.sass` -- I'm not 100% sure on this (I'd have to check)

**Comment by dahlia** [comment]
If we have auto-detection aware of the filename postfix, it should also have a way to explicitly turn it off.  I think it can be achieved by changing the default value of the `indented` parameter to `None` from `False`.  `None` means to use auto-detection, `True` means SASS, and `False` means SCSS.

**Comment by asottile** [comment]
I was off a bit here -- the `indented` keyword is only valid for `sass.compile(string=...)`.  For `sass.compile(filename=...)` or `sass.compile(dirname=...)` it is inferred according to `libsass`'s rules (guessed by file extension as far as I can tell).

**Comment by dahlia** [comment]
While the current implementation ignores the `indented` keyword when the `filename` parameter is used, it seems a little bug-prone.  We should change it to raise error when both `indented` and `filename` are specified at a time.

**Comment by dahlia** [comment]
🙈 So embarrassed that it is me who implemented that.

**Comment by asottile** [comment]
heh: https://github.com/sass/libsass-python/pull/111

**Comment by dahlia** [comment]
Lol it turns out I don't have to be embarrassed but more embarrassed now at a time. 🙄

**Comment by NoorMkdad** [comment]
Thanks!
