### ISSUE TITLE
Unable to build on Mac OSX with XCode 9

### ISSUE THREAD

**Issue by wrvdklooster** [sass/libsass-python#240]
With XCode 9 I am unable to build libsass.

I get following errors:
```
    In file included from libsass/src/ast.cpp:2:
    In file included from libsass/src/ast.hpp:14:
    In file included from libsass/src/ast_fwd_decl.hpp:11:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/unordered_map:369:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:19:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:321:9: error: no member named 'isless' in the global namespace
    using ::isless;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:322:9: error: no member named 'islessequal' in the global namespace
    using ::islessequal;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:323:9: error: no member named 'islessgreater' in the global namespace
    using ::islessgreater;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:324:9: error: no member named 'isunordered' in the global namespace
    using ::isunordered;
          ~~^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
    using ::isunordered;
          ~~^
    1 warning and 13 errors generated.
    error: command 'clang++' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of libsass
```

**Comment by asottile** [comment]
This is probably a problem upstream as well, and probably a problem with xcode itself.

Line 11 is simply:

```cpp
#include <unordered_map>
```

I'm going to try and get a mac and install xcode 9 to see if I can reproduce

Thanks for the issue!

**Comment by asottile** [comment]
I'm not able to reproduce on my machine:

```console
$ pip wheel libsass --no-binary :all:
Collecting libsass
  Using cached libsass-0.13.7.tar.gz
Collecting six (from libsass)
  Downloading six-1.11.0.tar.gz
Building wheels for collected packages: libsass, six
  Running setup.py bdist_wheel for libsass ... done
  Stored in directory: /private/tmp/wat
  Running setup.py bdist_wheel for six ... done
  Stored in directory: /private/tmp/wat
Successfully built libsass six
$ xcodebuild -version
Xcode 9.2
Build version 9C40b
$ clang++ --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by wrvdklooster** [comment]
Thanks for the quick reply. I ran same things as you did and get same error. Will look bit further into it also.
```
$ xcodebuild -version
Xcode 9.2
Build version 9C40b
Richard at MacBook-Pro-4 in ~/workspace/ah/python on release/V7.1*
$ clang++ --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by asottile** [comment]
@wrvdklooster curious if you can build this small program:

```cpp
#include <unordered_map>

int main() {
    std::unordered_map<int, int> x;
    return x.size();
}
```

```console
$ clang++ test.cpp -std=gnu++0x && ./a.out; echo $?
0
```

**Comment by wrvdklooster** [comment]
I checked and this looks OK.
```
$ cat test.cpp 
#include <unordered_map>

int main() {
    std::unordered_map<int, int> x;
    return x.size();
}
```
```
$ clang++ test.cpp -std=gnu++0x && ./a.out; echo $?
0
```

**Comment by wrvdklooster** [comment]
Still think it has something to do with my environment but can not figure out what.

Can this be related: https://forums.developer.apple.com/message/262481#262481?

**Comment by wrvdklooster** [comment]
When I add "-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk" I can compile the code.

For example: 
`$ clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I./libsass/include -I/Users/Richard/.pyenv/versions/3.5.2/include/python3.5m -c libsass/src/ast.cpp -o build/temp.macosx-10.13-x86_64-3.5/libsass/src/ast.o -c -O3 -fPIC -std=gnu++0x -Wall -Wno-parentheses -Werror=switch -stdlib=libc++ -mmacosx-version-min=10.7 -Wno-error=unused-command-line-argument-hard-error-in-future -DLIBSASS_VERSION="3.4.9" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
`

**Comment by wrvdklooster** [comment]
This seems to work:
```
export CPPFLAGS="-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/"
$ pip install libsass --upgrade
Collecting libsass
  Downloading libsass-0.14.2.tar.gz (309kB)
    100% |████████████████████████████████| 317kB 2.6MB/s 
Requirement already up-to-date: six in /Users/Richard/.pyenv/versions/3.5.2/envs/test/lib/python3.5/site-packages (from libsass)
Building wheels for collected packages: libsass
  Running setup.py bdist_wheel for libsass ... done
  Stored in directory: /Users/Richard/Library/Caches/pip/wheels/c8/7f/89/e0719cb55b82dde07c39fc6f6b023532cdff67431afb2fdc49
Successfully built libsass
Installing collected packages: libsass
  Found existing installation: libsass 0.13.6
    Uninstalling libsass-0.13.6:
      Successfully uninstalled libsass-0.13.6
Successfully installed libsass-0.14.2
```

**Comment by tobywf** [comment]
Could this be affecting wheel builds? There don't seem to be any macOS wheels [in releases](https://github.com/sass/libsass-python/releases) for versions since 0.13.7.

I noticed the package was taking a long time to install, but it worked in the end - maybe because I **don't** have XCode installed.

I wasn't able to find an issue on libsass, so they're either not aware, or it's not affecting upstream. Let me know if I can help in any way. Cheers!

**Comment by asottile** [comment]
Uploading macos wheels is a manual process and since none of my (primary, secondary, tertiary) computers are macos it tends to not get done :)

I'll go ahead and upload those right now!

(I still have a feeling this issue is somehow your computer's configuration, my very-vanilla macos doesn't suffer from the same problems)

**Comment by asottile** [comment]
I've uploaded cp27m and cp36m wheels

**Comment by wrvdklooster** [comment]
Thanks. Can you also upload cp35m?

**Comment by asottile** [comment]
Sure! How can I install py35?

**Comment by wrvdklooster** [comment]
I use https://github.com/pyenv/pyenv for installation and selection of Python versions.

**Comment by wrvdklooster** [comment]
Issue is solved with release 0.14.5. Closing.

**Comment by kakulukia** [comment]
I have the same error with version 0.20, but can install 0.19.4 without errors.

I get this while trying to install 0.20 on MacOS:

      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'isunordered' in the global namespace
    using ::isunordered;

**Comment by asottile** [comment]
I haven't had a chance to build the macos wheels since I no longer have a work laptop and my home networking is a little messed up right now (I've set up automation for the next release) -- I'll try and get the python wheels built again. Additionally, your macos toolchain setup is broken in some way I'm afraid

**Comment by kakulukia** [comment]
Do you have an idea what i might check to fix my eventually broken toolchain?

**Comment by asottile** [comment]
no sorry I don't really have the time to help for free right now, there might be something in the various linked issues -- or googling the error message though?

**Comment by asottile** [comment]
I've uploaded binary wheels for macos for 0.20 again, so that should be fixed now

**Comment by kakulukia** [comment]
thx, will test that tomorrow :)
