### ISSUE TITLE
libsass 0.14.5 fails to build

### ISSUE THREAD

**Issue by Traceur759** [sass/libsass-python#250]
When trying to build libsass 0.14.5, I receive this error, the function causing this doesn't seem to be defined anywhere.

pysass.cpp: In function ‘PyObject* _to_py_value(const Sass_Value*)’:
pysass.cpp:71:32: error: ‘sass_list_get_is_bracketed’ was not declared in this scope
             int is_bracketed = sass_list_get_is_bracketed(value);

**Comment by asottile** [comment]
How are you building this?

Here's the declaration of this function in the headers we're targeting : https://github.com/sass/libsass/blob/1e52b74306b7d73a617396c912ca436dc55fd4d8/include/sass/values.h#L119

**Comment by Traceur759** [comment]
I am using this command to build libsass:
python3 setup.py build

I am not able to see such line in that file under 0.14.5 tag.

**Comment by asottile** [comment]
That line is in the submodule, are you using any environment variables?

**Comment by Traceur759** [comment]
That explains a lot, I was using SYSTEM_SASS="true" and it seems that the system one is outdated.
Thank you very much for your help.

**Comment by asottile** [comment]
heh, it's almost like I called this ;) https://github.com/sass/libsass-python/pull/219#pullrequestreview-64638914

> It is not a pathway we want to support as version mismatches cause lots of problems (and `libsass` itself is quite the moving target).
