### ISSUE TITLE
libsass empty directory in source tarball

### ISSUE THREAD

**Issue by frediz** [sass/libsass-python#253]
Hi there!
would it be possible to remove the empty directory in the source tarball that is generated on the release page ?
Does it make sense to keep it in the release tarball ? I understand this is the submodules directory and ```git submodule update --init``` recreates the directory properly.
Thanks,
F.

**Comment by asottile** [comment]
I assume you're referring to the "Source code (tar.gz)"? This is generated by github so we have no control over it unfortunately

**Comment by asottile** [comment]
closing as per above, it's unfortunate but out of our control
