### ISSUE TITLE
SassMiddleware doesn't compile on request

### ISSUE THREAD

**Issue by maki-markie** [sass/libsass-python#255]
i have the following code, which i imported to run.py. It should compile my *.sass file to css upon reload/request of the webapp but it kinda doesnt work. It doesnt compile my sass files to css upon request. Is there something im missing here? I dont have any errors... Thanks alot!

```
from flask import Flask
from sassutils.wsgi import SassMiddleware
from myapp.config import Config


def create_app(config_class=Config):
    try:
        app = Flask(__name__)
        app.config.from_object(Config)

        app.wsgi_app = SassMiddleware(app.wsgi_app, {
            'myapp': ('static/sass', 'static/css', '/static/css')
        })

    except Exception as e:
        raise e
    else:
        from myapp.main.routes import main
        app.register_blueprint(main)

        return app
```

**Comment by asottile** [comment]
This definitely needs better docs :S -- it also suffers from #55 

Here's a quick example I threw together (I spent quite a while reading the code :/):

```python
from flask import Flask
from sassutils.wsgi import SassMiddleware


app = Flask(__name__)
app.wsgi_app = SassMiddleware(app.wsgi_app, {
    'app': ('static/sass', 'static/css', '/static/css')
})

app.run('127.0.0.1', debug=True)
```

```
$ tree static/
static/
└── sass
    └── main.scss
```

```
a { b: c; }
```

```
python app.py
```

```
$ curl localhost:5000/static/css/main.scss.css && echo
a {
  b: c; }

/*# sourceMappingURL=../css/main.scss.css.map */
```

**Comment by maki-markie** [comment]
Hi Anthony!
Thanks for the quick reply... But it still doesn't work. My run.py looks like this:

```
from myapp import create_app

app = create_app()

if __name__ == '__main__':
    app.run('127.0.0.1:5000', debug=True)
```

**Comment by asottile** [comment]
The static directory must be rooted inside the myapp package (I was using a single file module so I didn't need a package)

**Comment by maki-markie** [comment]
it is. my structure looks like this:

myapp
   static
       sass
       css
   templates

**Comment by asottile** [comment]
What url are you requesting?

**Comment by maki-markie** [comment]
i tried both:
localhost:5000 and
http://127.0.0.1:5000/
both doesnt compile my sass file to css file in the static/css folder

**Comment by asottile** [comment]
Paste your whole `curl` command, I'm more interested in the path than the domain

**Comment by maki-markie** [comment]
im very new to flask and python. and im developing under windows 10 platform. the documentation said the 
```
from flask import Flask
from sassutils.wsgi import SassMiddleware


app = Flask(__name__)
app.wsgi_app = SassMiddleware(app.wsgi_app, {
    'app': ('static/sass', 'static/css', '/static/css')
})
```
should compile the sass/scss files to css upon the request or reload of the page. which when i load the page on the browsers. but it doesnt compile my sass/scss files when i run my run.py or reload the page.

**Comment by asottile** [comment]
It will only compile the files if you request urls that would lead to those files.

For instance, if I have this:

```
myapp/
    static/
        sass/
             foo.scss
```

I'd need to request

```
http://localhost:5000/static/css/foo.scss.css
```

And _then_ it will on-the-fly compile a file, place it at static/css/foo.scss.css, and then serve it

**Comment by maki-markie** [comment]
sorry Anthony, but this doesn't make any sense nor take the extra work in development phase. What if, if i have multiple sass/scss files that i want to compile to css?

Isn't much better if it automaticly compile all the sass/scss files to css on upon request/load of http://localhost:5000/ ?

**Comment by asottile** [comment]
The entire goal of the `SassMiddleware` is so that you get on-the-fly compile of files as they are needed.  There'd be no reason to compile a sass file if it wasn't served to a webpage right?  Additionally when you make edits to your scss files they'll be reflected as soon as you reload (instead of having to use some other build tool to regenerate everything for every file you change).

**Comment by maki-markie** [comment]
exactly! so why do i need to request for: http://localhost:5000/static/css/foo.scss.css then?
if i have foo1.sass and foo2.sass and i need both of those sass files to be compile to css? how does the request will look like on the browser then?

**Comment by asottile** [comment]
you don't directly, the hope is that you're serving some sort of html page which has `<link rel="stylesheet" href="/static/css/foo.scss.css">`

**Comment by maki-markie** [comment]
yeah, i do. i misunderstood the documentation. i thought the functionality was, it will compile all my sass/scss file to the css folder upon the request of the` localhost:5000 `
does the `<link rel="stylesheet" href="/static/css/foo.scss.css">` also work in production enviroment?

**Comment by asottile** [comment]
`SassMiddleware` is not suggested for production -- it would work, but you're going to be better off pre-compiling your assets and using a CDN.

**Comment by maki-markie** [comment]
one last question about this topic. how do i deactivate the compiler to produce the `*.sass.css.map`? and does the copiler always compile the sass files with `*.sass.css `or can i set it just to `*.css`?

**Comment by asottile** [comment]
it looks like source maps are [always on](https://github.com/sass/libsass-python/blob/f05a9b4933b21d4c33160b61c1378eb6bc592d72/sassutils/wsgi.py#L130) with no way to turn them off.  This is probably by design since it's intended as a _developer_ tool.

The extension thing is the issue I mentioned previously: #55 (an outstanding (imo) bug)

**Comment by maki-markie** [comment]
Thanks a lot Anthony! You were a great help... But i think im much better off with `sass.compile` command.
