### ISSUE TITLE
libsass wont compile SASS/SCSS file in Blueprint with own static folder

### ISSUE THREAD

**Issue by maki-markie** [sass/libsass-python#257]
hi there!

i have this folder structure:

```
.app
-- blueprint1
-----templates
-----static
--------css
--------sass
--templates
--static
----css
----sass
```

when i link the `<link rel="stylesheet" type="text/css" href="{{ url_for('blueprint1.static', filename='css/test.sass.css') }}">`
it doesnt compile the sass/scss file to css folder in the static/css folder of the blueprint1

am i missing something here? Thanks

```
% extends "base.html" %}
{% block title %}Test{% endblock title %}
{% block head %}
{{ super() }}
    **<link rel="stylesheet" type="text/css" href="{{ url_for('blueprint1.static', filename='css/test.sass.css')** }}">
{% endblock %}

{% block content %}
<p> Test
{% endblock %}
```

**Comment by asottile** [comment]
How are you configuring the Middleware?

**Comment by maki-markie** [comment]
i got it running with:

```
app.wsgi_app = SassMiddleware(app.wsgi_app, {
            'app': ('static/sass', 'static/css', '/static/css'),
            'app.bp1': ('static/sass', 'static/css', '/bp1/static/css')
        })
```
or is there any optimal way to do this?

**Comment by asottile** [comment]
I think what you'd need here is:
```python
app.wsgi_app = SassMiddleware(app.wsgi_app, {
    'app': ('static/sass', 'static/css', '/static/css'),
    'app.blueprint1': ('static/sass', 'static/css', '/blueprint1/static/css'),  # or whatever your blueprint url is for the third arg
})
```

**Comment by asottile** [comment]
lol, nice race :)

**Comment by maki-markie** [comment]
Anthony, any news on the #55? Is there a way now to compile sass/scss files just with *.css?

**Comment by maki-markie** [comment]
did you give it up already? :)  the problems seems to trivial, i wish my python expertise are very good but its not :(

**Comment by asottile** [comment]
hah no I just haven't had the time to attempt it beyond that -- real life and such :)  -- maybe tonight I'll take a stab at it

**Comment by asottile** [comment]
ah yeah it got merged: https://github.com/sass/libsass-python/pull/258

going to make a release soon! if you want, try it out by installing from `git`: `pip install git+https://github.com/sass/libsass-python`

**Comment by maki-markie** [comment]
Yay! Youre the best! :)
