### ISSUE TITLE
Watch recommendations

### ISSUE THREAD

**Issue by tehfink** [sass/libsass-python#263]
I saw that the `watch` functionality was removed in #203, and a request was made for [documenting a replacement](https://github.com/sass/libsass-python/issues/155#issuecomment-235419540). What's the recommended method to watch for sass file changes?

**Comment by asottile** [comment]
I've heard good things about [watchman](https://facebook.github.io/watchman/docs/install.html) but as far as I know no specific watcher has been documented.

**Comment by tehfink** [comment]
@asottile Thanks for the reply. The Boussole project has been working well for me, [with some tweaks](https://github.com/sveetch/boussole/issues/31).
