### ISSUE TITLE
Support embedding sources' contents

### ISSUE THREAD

**Issue by shadow-light** [sass/libsass-python#268]
From what I can tell, libsass supports embedding the contents of source files in a source map and also embedding the source map as a data uri at the end of CSS output.

https://github.com/sass/libsass/pull/591

Any chance this could be supported in libsass-python?

**Comment by asottile** [comment]
Yeah looks like it would just need to call sass_context_set_source_map_embed based on a boolean parameter

**Comment by asottile** [comment]
@shadow-light do you want to take a stab at this or shall I?

**Comment by shadow-light** [comment]
If I can implement it in python I'd be happy to, but I'm not familiar with C++ and don't want to mess it up :)

**Comment by asottile** [comment]
ah yeah you'd have to write a little bit of C to thread it through -- let me see if I can't find you a similar PR that you could take as example

**Comment by asottile** [comment]
Here's one which adds a sequence (more complicated than you need): https://github.com/sass/libsass-python/pull/246
Here's a similar one which adds a boolean that gets passed through: https://github.com/sass/libsass-python/pull/102
