### ISSUE TITLE
build fails on Mac OS Mojave

### ISSUE THREAD

**Issue by christianAESD** [sass/libsass-python#270]
It seems libstdc++ has been removed and replaced by libc++

ld: library not found for -lstdc++

**Comment by asottile** [comment]
strange! it appears to work for me, but perhaps I haven't upgraded to the latest xcode yet.

**Comment by asottile** [comment]
@christianAESD can you try #271 for me?

```
pip install git+https://github.com/asottile/libsass-python@lcpp_macos
```

**Comment by christianAESD** [comment]
Yes that works. tested with python 3.7

**Comment by shamilovtim** [comment]
This doesn't resolve the problem for me. Branch has been merged into master. Cloning from master still results in same error:
 `ld: library not found for -lstdc++`.
