### ISSUE TITLE
Reports wrong variable name in sass.CompileError exception message

### ISSUE THREAD

**Issue by michael-angelozzi** [sass/libsass-python#299]
## input.scss

```scss
// $color__second is undefined, note underscores not dash
color:       $color__second;
```

## Actual results
```Syntax error:
Error: Undefined variable: "$color--second".
        on line 93:18 of ../src/base/assets/sass/_bb__base-base.scss```
```
## Expected result
```Syntax error:
Error: Undefined variable: "$color__second".
        on line 93:18 of ../src/base/assets/sass/_bb__base-base.scss
```
Note!! Incorrectly reports variable name with dashes instead of underscores

version info:
Using python libsass:
```
>>> sass.__version__
'0.19.2'
```

Correct variable name is reported when using: http://libsass.ocbnet.ch/srcmap

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==

**Comment by asottile** [comment]
we're just a thin wrapper around [libsass](https://github.com/sass/libsass) -- I'd suggest reporting this there
