### ISSUE TITLE
Wrong compile warning since version 0.19.3 'compound selectors may no longer be extended'

### ISSUE THREAD

**Issue by dwt** [sass/libsass-python#303]
To trigger this, try to feed this to the sass compiler:

```
sass.compile(string='''
.form-control[disabled] {
    display: block;
}
.select2-container--disabled {
    @extend .form-control[disabled];
}
''')
```

This is tested with libsass 0.19.3. Feeding this to the sass compiler will emit this warning:

```
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
```

I think there are several things wrong with this warning message.

a) the URL doesn't lead to where it should, it resolves to <https://sass-lang.com/documentation> instead of the correct <https://sass-lang.com/documentation/breaking-changes/extend-compound>

b) the 'Consider...' message is a bit confusing. I think it would be clearer to state 'Consider joining the css classes by commas to document instead.'

c) the message doesn't give any context of file and line number, making it very hard to actually fix anything.

d) as my example shows, this seems to be raised even if it doesn't apply, as there is no compound selector in my example.

**Comment by asottile** [comment]
we're just a wrapper around https://github.com/sass/libsass, please report your issue there, thanks!

**Comment by dwt** [comment]
Reported here: https://github.com/sass/libsass/issues/2998
