### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by pmsoltani** [sass/libsass-python#311]
Hi

Looks like there is a typo in [Building Sass/SCSS for each deployment](https://sass.github.io/libsass-python/frameworks/flask.html#building-sass-scss-for-each-deployment) section of the docs (replaced ~had~ with **a**):

> If libsass has been installed in the `site-packages` (for example, your virtualenv), `setup.py` script also gets ~had~ **a** new command provided by libsass: **`build_sass`**. The command is aware of **the** `sass_manifests` option of `setup.py` and builds all Sass/SCSS sources according to the manifests.

I think you should also throw in a "the" before `sass_manifests` in the last line for good measure.

Thanks

**Comment by asottile** [comment]
please send a patch, no need to make an issue for typos
