### ISSUE TITLE
Settings strip_extension for SassMiddleware

### ISSUE THREAD

**Issue by Xevion** [sass/libsass-python#316]
I feel like I'm missing something, as the warning I'm being given seems to imply the solution is obvious, but the solutions I found are not working, or seemingly properly documented.

The warning I am getting is of course about `strip_extension` not being set and defaulting to `False`.

```
C:\Users\Xevion\.virtualenvs\app_name\lib\site-packages\sassutils\builder.py:166: FutureWarning: `strip_extension` was not specified, defaulting to `False`. In the future, `strip_extension` will default to `True`.
```

Combing through GitHub Issues and PRs, I found the following:

```python
app.wsgi_app = SassMiddleware(
    app.wsgi_app,
    {
        'app_name': {
            'sass_path': 'static/sass',
            'scss_path': 'static/css',
            'wsgi_path': '/static/css',
            'strip_extension': False
        }
    }
)
```

Unfortunately, this doesn't even get off the ground, erroring with a unexplainable syntax error:

```python
127.0.0.1 - - [22/Jul/2020 02:38:45] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Xevion\.virtualenvs\app_name\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Xevion\.virtualenvs\app_name\lib\site-packages\flask\cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "C:\Users\Xevion\.virtualenvs\app_name\lib\site-packages\flask\cli.py", line 119, in call_factory
    return app_factory()
  File "F:\Programming\Python\Projects\app_name\app_name\create_app.py", line 26, in create_app
    'strip_extension': False
  File "C:\Users\Xevion\.virtualenvs\app_name\lib\site-packages\sassutils\wsgi.py", line 102, in __init__
    self.manifests = Manifest.normalize_manifests(manifests)
  File "C:\Users\Xevion\.virtualenvs\app_name\lib\site-packages\sassutils\builder.py", line 124, in normalize_manifests
    manifest = Manifest(**manifest)
TypeError: __init__() got an unexpected keyword argument 'scss_path'
```

I was about to give up when I figured out that the Middleware patch on the documentation works if I simply add a boolean to the end, just like the dictionary was setup.

```python
app.wsgi_app = SassMiddleware(app.wsgi_app, {
    'app_name': ('static/sass', 'static/css', '/static/css', False)
})
```

Let me know if I've found a problem with documentation or if I've missed a very important and obvious detail. I believe this should be better addressed, as clearly I missed it. Still not sure why the dictionary version failed; sounds like it meant there was a dictionary and tuple configuration available. Additionally, the `w` in `SassMiddleware` is changed to lowercase nowadays.

https://github.com/sass/libsass-python/issues/55#issuecomment-446895109
https://sass.github.io/libsass-python/frameworks/flask.html#building-sass-scss-for-each-request

**Comment by asottile** [comment]
so close!  from [these docs](https://sass.github.io/libsass-python/sassutils/distutils.html) the format is `'css_path': ...` not `'scss_path': ...`

**Comment by Xevion** [comment]
> 
> 
> so close! from [these docs](https://sass.github.io/libsass-python/sassutils/distutils.html) the format is `'css_path': ...` not `'scss_path': ...`

Ah. I see. That is an annoyingly painful mistake.

```python
app.wsgi_app = SassMiddleware(
    app.wsgi_app,
    {
        'app_name': {
            'sass_path': 'static/sass',
            'css_path': 'static/css',
            'wsgi_path': '/static/css',
            'strip_extension': False
        }
    }
)
```

This works for me.
