### ISSUE TITLE
Mac wheels are missing in PyPI

### ISSUE THREAD

**Issue by peterdemin** [sass/libsass-python#317]
README states, that wheels for Mac are provided, but PyPI doesn't have them: https://pypi.org/project/libsass/#files
![image](https://user-images.githubusercontent.com/1448666/91497361-e0edcb00-e88b-11ea-95b0-f619f6815653.png)

LMK if I can help building Mac wheels.

**Comment by asottile** [comment]
I see them in your screenshot?

**Comment by peterdemin** [comment]
Ah, I guess it's just Python3.6 and Mac is missing

**Comment by asottile** [comment]
yeah I probably didn't have python3.6 around when I built it, do you need python3.6?

**Comment by peterdemin** [comment]
Yes, I'm still using it :-)

**Comment by asottile** [comment]
should be there in 0.20.1

**Comment by peterdemin** [comment]
I confirm:
```
$ pip install libsass
Collecting libsass
  Downloading libsass-0.20.1-cp36-abi3-macosx_10_14_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 469 kB/s
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, libsass
Successfully installed libsass-0.20.1 six-1.15.0
```
Thanks, Anthony!

BTW it was a bit of surprise to see you maintaining this project. I know and use your other tools, most notably pre-commit. How do you manage to find the time for all these great open source projects?

**Comment by asottile** [comment]
lol at the moment I have time because I was affected by layoffs :(
