### ISSUE TITLE
LibSass is deprecated

### ISSUE THREAD

**Issue by e1mo** [sass/libsass-python#326]
As of October, [LibSass is officially deprecated](https://sass-lang.com/blog/libsass-is-deprecated). Is there an upgrade-path for this role to [`dart-sass`](https://sass-lang.com/dart-sass) which is the new recommended default?

**Comment by asottile** [comment]
The title of that article is clickbait, libsass isn't actually going anywhere, dart-sass is just the "official" reference implementation

**Comment by e1mo** [comment]
To quote from the Article:

- We recommend all existing LibSass users make plans to eventually move onto Dart Sass, and that all Sass libraries make plans to eventually drop support for LibSass.
- We’re no longer planning to add any new features to LibSass, including compatibility with new CSS features.

Whilst it is not dead and will still be maintained, no new features will be added and therefore compatibility with the official css and sass spec is expected to suffer. But since libsass was only deprecatd 2 Months ago, I would assume that it will continue working for some time.  Maybe we could rephrase this issue to a long term plan on how to migrate to dart-sass before libsass will reach that certain breakpoint?

**Comment by asottile** [comment]
yeah I kinda suspect this choice will break the community -- notably there isn't a library binding to dart-sass so it will likely fail to replace libsass as it is (imo) overly-optimistically predicted in the article

**Comment by vadimkantorov** [comment]
Related: https://github.com/sass/dart-sass/issues/2166#issuecomment-1915715290

**Comment by asottile** [comment]
there's no such library binding still.  that comment means nothing without dart being able to produce an aot c-callable shared object

**Comment by asottile** [comment]
that sounds awful, at that point you might as well subprocess

**Comment by vadimkantorov** [comment]
Ha-ha, of course I can subprocess, but being able to have a Python-module embedding Dart/AOT would be torturingly nice :)
