### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [sass/libsass-python#347]
Problem
---------
On aarch64, pip install libsass builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install libsass should be able to download the wheels from pypi

@asottile, Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by asottile** [comment]
dupe #341

**Comment by asottile** [comment]
also I think you'll recall our discussion here: https://github.com/hynek/argon2-cffi/pull/74

**Comment by aaugustin** [comment]
Hello, I just wasted a stupid amount of time figuring out why pip wouldn't install libsass from wheels in a container and chose to install from source instead:

```
$ docker run -it --rm python:3.10-slim /bin/bash
root@187d1396c785:/# pip install libsass
Collecting libsass
  Downloading libsass-0.21.0.tar.gz (317 kB)
...
      error: command 'gcc' failed: No such file or directory
...
...
```

Of course, the workaround is "just" `apt-get install build-essentials` in my Dockerfile. Is it really a good trade-off to have all your users to jump through this hoop, though?

I can understand your argument about publishing potentially non-compliant wheels. The counter-argument would be:

- Until there's a standard, there's no risk of being non-compliant.
- When there's a standard, at worst, you can bump the version number and publish compliant wheels. I wouldn't expect the previous, potentially non-compliant, to cause significant harm. At least, not enough to outweigh the convenience of being able to install libsass without jumping through hoops.

In case it helps, cibuildwheel + GitHub actions makes it easy to create aarch64 wheels (among many others). I understand that you aren't currently using that toolchain, perhaps for good reasons. I'm not an expert here, just a maintainer of a few Python packages and user of libsass :-)
