### ISSUE TITLE
SASS compilation broken, SCSS still works in latest version?

### ISSUE THREAD

**Issue by charludo** [sass/libsass-python#352]
Just encountered this error:
```
sass.CompileError: Error: Invalid CSS after "...[last line of file]": expected 1 selector or at-rule, was "{}"
```

Neither my project, nor the .sass file have changed since the last time I compiled the file, but libsass and libsass-python have both received updates. Some testing with simple files containing only one rule yielded the same result.

I remember getting the same error a while back, which was solved by passing `indented=True` to `sass.compile()`. This doesn't seem to do anything though.

Compiling SCSS still works, however.

**Comment by charludo** [comment]
....I'm an idiot.

Your example worked.

Something in another API changed in the meantime, and I accidentally fed sass.compile() first raw sass (worked) then the compiled css (obviously does not work).

Sorry for bothering you.

**Comment by asottile** [comment]
no problem!
