### ISSUE TITLE
Release version with wheels for python > 3.7

### ISSUE THREAD

**Issue by RemiDesgrange** [sass/libsass-python#448]
Hi, thanks for this project 🙏 

Could you make a release on pypi.org with wheels for more recent version of python (currently 3.7 on pypi).

Thx !

**Comment by asottile** [comment]
the wheels on pypi are [abi3](https://youtu.be/4uy0c855msk) meaning they work for any version newer than the minimum one on pypi -- the whole point of abi3 is so that I don't need to continually upload newer wheels

**Comment by RemiDesgrange** [comment]
Oh 😭 sorry...
