### ISSUE TITLE
Is '@use' supported?

### ISSUE THREAD

**Issue by nolankramer** [sass/libsass-python#458]
I'm using [qtsass](https://github.com/spyder-ide/qtsass/tree/master), which relies on libsass here to `compile(**kwargs)` with `custom_function`, `importers`, and `include_paths`.

According to the docs, it looks like `include_paths` should cover usage of `@import`. But it looks like my scss files are failing to compile with `@use`. I'm wondering if that's supported by this python package?

**Comment by nolankramer** [comment]
The issue happens to be in qtsass, which iterates over files, instead of using the directory-style compile() in libsass

**Comment by nolankramer** [comment]
Re-opened because I gained understanding that qtsass was including directories correctly. The `@use` should have been resolved.

All evidence points to `@use` not functioning correctly due to how this library wraps libsass.

**Comment by asottile** [comment]
as per https://github.com/sass/libsass-python/issues/402#issuecomment-1219996747
