### ISSUE TITLE
Missing wheel for Linux ARM64

### ISSUE THREAD

**Issue by kraptor** [sass/libsass-python#475]
Same as #450, but for Linux.

Normally the compilation doens't break as far as Python devel packages are installed, but this can be annoying for embedded devices.

Is it possible to have wheels for Linux ARM64?

Currently, there is only libsass-0.23.0-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.whl

Thank you!

**Comment by asottile** [comment]
and actually the same as #341 please search better next time!
