### ISSUE TITLE
Strip Sass extension from output file

### ISSUE THREAD

**Issue by le717** [sass/libsass-python#55]
Using this simple script here:

``` python
import sassutils.builder

result = sassutils.builder.build_directory(".", ".", "compressed")
print(result)  # Outputs {'style.scss': 'style.scss.css'}
```

And indeed, the output file name is `style.scss.css`. Ideally it should be called simply `style.css`. :)

**Comment by asottile** [comment]
Oh hey it looks like we have two implementations of the same thing.  sass.complie (directory=...) seems to do what toy want.  We should probably delete the duplicated code.

**Comment by le717** [comment]
Sweet! I didn't see the `directory` parameter in the documentation, so when I saw the description for `sassutils.builder` ("Build the whole directory"), I went straight for that. Thanks for the quick answer! :smile:

**Comment by maki-markie** [comment]
hi there!
is this a official release already?
thanks

**Comment by asottile** [comment]
not yet -- soon!

**Comment by asottile** [comment]
[0.15.0](https://github.com/sass/libsass-python/releases/tag/0.15.0) has been released with this option available :tada:

**Comment by asottile** [comment]
This can now be turned off with `strip_extension=True` -- in a future version that will be the default

**Comment by maki-markie** [comment]
@asottile hi anthony! how to use strip_extension with SassMiddleware?
```
    app.wsgi_app = SassMiddleware(
        app.wsgi_app,
        {
            'main': ('static/sass', 'static/css', '/static/css'),
            'main.users': ('static/sass', 'static/css', '/users/static/css')
        }
    )
```

**Comment by asottile** [comment]
You'll use the dictionary form, I believe it's something like this:

```python
SassMiddleWare(
    app.wsgi_app,
    {
        'main': {
            'sass_path': 'static/sass',
            'scss_path': 'static/css',
            'wsgi_path': '/static/css',
            'strip_extension': True,
        },
        'main.users': {
            'sass_path': 'static/sass',
            'scss_path': 'static/css',
            'wsgi_path': '/users/static/css',
            'strip_extension': True,
        },
    },
)

**Comment by maki-markie** [comment]
@asottile that worked out! But why i still need to call the css file like:
`<link rel="stylesheet" type="text/css" href="{{ url_for('users.static', filename='css/login.**sass**.css') }}">`
and not like this:
`<link rel="stylesheet" type="text/css" href="{{ url_for('users.static', filename='css/login.css') }}">`
when my SassMiddleware is in the __init__.py

**Comment by asottile** [comment]
you... shouldn't? that's weird

**Comment by maki-markie** [comment]
@asottile shouldn't do the first one or the second option? :D

**Comment by asottile** [comment]
The second one looks right to me

**Comment by maki-markie** [comment]
exactly! but it doesnt worked. it doesn't generate the *.css file from sass

**Comment by asottile** [comment]
do you have a repository I can look at? I don't actually have any uses of `SassMiddleware` on hand

**Comment by maki-markie** [comment]
sadly, i cannot share the data :(  but my init file looks like this:

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_migrate import Migrate
from sassutils.wsgi import SassMiddleware

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'
migrate = Migrate()


def create_app(config_class=DevelopmentConfig):
    try:
        app = Flask(__name__)
        app.config.from_object(config_class)
        with app.app_context():
            db.init_app(app)
        bcrypt.init_app(app)
        login_manager.init_app(app)
        migrate.init_app(app, db)

        app.wsgi_app = SassMiddleware(
            app.wsgi_app,
            {
                'mis': {
                    'sass_path': 'static/sass',
                    'css_path': 'static/css',
                    'wsgi_path': '/static/css',
                    'strip_extension': True
                },
                'mis.users': {
                    'sass_path': 'static/sass',
                    'css_path': 'static/css',
                    'wsgi_path': '/users/static/css',
                    'strip_extension': True
                }
            }
        )
    except Exception as e:
        raise e
    else:
        from mis.users.routes import users
        app.register_blueprint(users)

        return app

```

**Comment by asottile** [comment]
damn, you're right -- I debugged this and it looks like it's _still_ not being honored for the middleware, let me get yet another patch for this -- sorry again 😭

**Comment by asottile** [comment]
@maki-markie can you try out the branch for #274?

**Comment by maki-markie** [comment]
@asottile yup. ill try this later today and let you know...

**Comment by maki-markie** [comment]
@asottile sorry anthony couldn't find time yesterday. could you able to test it ?

**Comment by asottile** [comment]
you can install from `git` yeah, I'm planning on making a release soon with libsass 3.5.5  -- maybe today

**Comment by asottile** [comment]
0.16.0 is released which should have a fix for that!

**Comment by maki-markie** [comment]
@asottile did you test it again? i did with the 0.16.0 and it didnt worked :(

**Comment by maki-markie** [comment]
@asottile i dont know if im wrong but i dont see any support for `*.sass` files in `https://github.com/sass/libsass-python/blob/master/sassutils/builder.py`

```
 def unresolve_filename(self, filename):
        """Retrieves the probable source path from the output filename.  Pass
        in a .css path to get out a .scss path.
        :param filename: the css filename
        :type filename: :class:`str`
        :returns: the scss filename
        :rtype: :class:`str`
        """
        filename, _ = os.path.splitext(filename)
        if self.strip_extension:
            filename = filename + '.scss'
        return filename
```

This doesnt generate a *.css file from a *.sass file anymore in version 0.16.0
 `<link rel="stylesheet" type="text/css" href="{{ url_for('users.static', filename='css/login.sass.css') }}">`
NOR this
`<link rel="stylesheet" type="text/css" href="{{ url_for('users.static', filename='css/login.css') }}">`

**Comment by asottile** [comment]
Indeed, it does not support .sass, not quite sure how to implement that :S

**Comment by maki-markie** [comment]
@asottile it worked before 0.16.0 tho... 
`<link rel="stylesheet" type="text/css" href="{{ url_for('users.static', filename='css/login.sass.css') }}">`
maybe add: `filename = filename + '.sass' `:D

**Comment by maki-markie** [comment]
@asottile youre right. my mistake. i have strip_extension on=True. Is the *.sass support will be implemented also? i really hate the *.scss because of all the bracets.
why is that so hard to implement the *.sass support?

**Comment by asottile** [comment]
It's probably not hard, I just haven't put any thought into it :laughing: (and unfortunately I don't use .sass which is why I didn't notice it or think about it)

**Comment by maki-markie** [comment]
@asottile just make another if statement for *.sass and everything is solved. lol

**Comment by maki-markie** [comment]
@asottile are you planing to do the *.sass support or will this be ever implemented? thanks

**Comment by maki-markie** [comment]
@asottile so finally had time to check up... is there a fix for *.sass already? I tried the newest version 0.16.1 but it wont compile the sass file when i call for this:
`<link rel="stylesheet" type="text/css" href="{{ url_for('users.static', filename='css/login.css') `
with the `'strip_extension': True`

**Comment by asottile** [comment]
there's a test [demonstrating it works](https://github.com/sass/libsass-python/blob/889f0ba77cd02a7a8bb2e40f8a1e1044be6b2c97/sasstests.py#L755-L779) so it should work.  I suspect you've got a configuration problem?

**Comment by maki-markie** [comment]
@asottile did you test it in a live-code? My configuration works totally fine.

```
    app.wsgi_app = SassMiddleware(
        app.wsgi_app,
        {
            'mis_dash': {
                'sass_path': 'static/sass',
                'css_path': 'static/css',
                'wsgi_path': '/static/css',
                'strip_extension': True
            }
        }
    )
```
Then I call this in a Template:
`<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/grid.css') }}">`

But this doesn't generate the desired *.css file.

But if I set the strip_extension to false and call the link like
`<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/grid.sass.css') }}">`
then it does generate the *.css file. But as we have talk before it shouldn't be like that with the update anymore.

**Comment by asottile** [comment]
ok I think I know what's happening.  It works while in `.` but not in a subdir.  Let me get a patch for it :sigh:

**Comment by asottile** [comment]
@maki-markie can you try out this branch please? https://github.com/sass/libsass-python/pull/280
